export type Domain = "finance" | "nyc" | "games" | "music" | "tools" | "data";

export interface Project {
  name: string;
  slug: string;
  tagline: string;
  domain: Domain;
  tech: string[];
  date: string;
  url: string;
  liveUrl: string | null;
  flagship: boolean;
  image?: string;
}

export const projects: Project[] = [
  // ── Flagship Projects ──────────────────────────────────────────────
  {
    name: "Festival Optimizer",
    slug: "festival-optimizer",
    tagline: "Compare music festival trips by total cost from your airport.",
    domain: "finance",
    tech: ["Next.js", "TypeScript", "Amadeus API", "SerpApi", "Ticketmaster API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/festival-optimizer",
    liveUrl: "https://festival-optimizer-app.vercel.app",
    flagship: true,
    image: "/cards/festival-optimizer.png",
  },
  {
    name: "Menswear Market Pulse",
    slug: "menswear-market-pulse",
    tagline: "Real-time menswear intelligence dashboard tracking trends across brands and markets.",
    domain: "data",
    tech: ["React", "TypeScript", "API Aggregation", "Charts"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/menswear-market-pulse",
    liveUrl: "https://menswear-intel.vercel.app",
    flagship: true,
    image: "/cards/menswear.png",
  },
  {
    name: "Shock Cascade",
    slug: "shock-cascade",
    tagline: "Macro risk simulator. Model a disruption, trace cascade effects through sectors, map exposure to a portfolio.",
    domain: "finance",
    tech: ["React", "TypeScript", "D3.js", "Causal Graphs"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/shock-cascade",
    liveUrl: "https://shock-cascade-rebuild.vercel.app",
    flagship: true,
    image: "/cards/shock-cascade.png",
  },

  // ── Finance & Data ─────────────────────────────────────────────────
  {
    name: "Narrative Edge",
    slug: "narrative-edge",
    tagline: "Retail trading intelligence combining Reddit narrative signals with cross-source confirmation.",
    domain: "finance",
    tech: ["React", "TypeScript", "Reddit API", "NLP"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/narrative-edge",
    liveUrl: "https://narrative-edge.vercel.app",
    flagship: false,
  },
  {
    name: "Fulcrum Finder",
    slug: "fulcrum-finder",
    tagline: "Financial distress screener. Surface companies near tipping points before consensus catches on.",
    domain: "finance",
    tech: ["React", "TypeScript", "Recharts", "Financial APIs"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/fulcrum-finder",
    liveUrl: "https://fulcrum-finder.vercel.app",
    flagship: false,
  },
  {
    name: "Card Scout",
    slug: "card-scout",
    tagline: "Gift card deal monitor with live scraper ingestion, outlier scoring, and watchlists.",
    domain: "finance",
    tech: ["React", "TypeScript", "Web Scraping"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/card-scout",
    liveUrl: "https://card-scout.vercel.app",
    flagship: false,
  },
  {
    name: "VintageMap",
    slug: "vintagemap",
    tagline: "Wine vintage explorer. Enter a meaningful year, see wine region quality on an interactive world map.",
    domain: "data",
    tech: ["React", "Mapbox", "Wine API"],
    date: "2026-02",
    url: "https://github.com/michaelpyon/VintageMap",
    liveUrl: "https://vintage-map.vercel.app",
    flagship: false,
  },
  {
    name: "Game Pulse",
    slug: "game-pulse",
    tagline: "Gaming industry pulse tracker. Trends, sentiment, and market signals across publishers.",
    domain: "games",
    tech: ["React", "TypeScript", "API Aggregation"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/game-pulse",
    liveUrl: "https://game-pulse.vercel.app",
    flagship: false,
  },

  // ── NYC ────────────────────────────────────────────────────────────
  {
    name: "The Low Line",
    slug: "subway-shame",
    tagline: "NYC subway delay tracker. Real-time severity scores for every line.",
    domain: "nyc",
    tech: ["React", "MTA API", "Node.js"],
    date: "2026-02",
    url: "https://github.com/michaelpyon/subway-shame",
    liveUrl: "https://subway-shame.vercel.app",
    flagship: false,
  },
  {
    name: "Pulse NYC",
    slug: "pulse-nyc",
    tagline: "Neighborhood-change dashboard combining live city signals into development pressure and nightlife activation scores.",
    domain: "nyc",
    tech: ["React", "TypeScript", "NYC Open Data"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/pulse-nyc",
    liveUrl: "https://pulse-nyc.vercel.app",
    flagship: false,
  },
  {
    name: "Random Pin Cuisine",
    slug: "random-pin-cuisine",
    tagline: "Drop a pin anywhere on a world map and find matching NYC restaurants with Michelin and critic badges.",
    domain: "nyc",
    tech: ["React", "Mapbox", "Google Places API"],
    date: "2026-02",
    url: "https://github.com/michaelpyon/random-pin-cuisine",
    liveUrl: "https://random-pin-cuisine.vercel.app",
    flagship: false,
  },
  {
    name: "Pollen Season",
    slug: "pollen-season",
    tagline: "NYC pollen forecast for allergy sufferers. Daily counts and 5-day outlook.",
    domain: "nyc",
    tech: ["React", "TypeScript", "Weather API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/pollen-season",
    liveUrl: "https://pollen-season.vercel.app",
    flagship: false,
  },
  {
    name: "NYC BlockScore",
    slug: "nyc-blockscore",
    tagline: "Apartment hunting tool. Aggregates StreetEasy rents, walk scores, 311 complaints, and restaurant density by block.",
    domain: "nyc",
    tech: ["React", "TypeScript", "StreetEasy", "NYC Open Data"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/nyc-blockscore",
    liveUrl: "https://nyc-blockscore-app.vercel.app",
    flagship: false,
  },
  {
    name: "ArchiMap",
    slug: "archimap",
    tagline: "Interactive map of curated NYC architecture walks. Explore landmark buildings by neighborhood.",
    domain: "nyc",
    tech: ["React", "Mapbox", "TypeScript"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/archimap",
    liveUrl: "https://archimap-pink.vercel.app",
    flagship: false,
  },
  {
    name: "Architecture Tour",
    slug: "architecture-tour",
    tagline: "Self-guided NYC architecture walking tours with historical context and landmark details.",
    domain: "nyc",
    tech: ["React", "TypeScript", "Mapbox"],
    date: "2026-02",
    url: "https://github.com/michaelpyon/architecture-tour",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Gap Finder NYC",
    slug: "gap-finder-nyc",
    tagline: "Find underserved neighborhoods and business gaps across NYC using open data.",
    domain: "nyc",
    tech: ["Next.js", "TypeScript", "NYC Open Data"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/gap-finder-nyc",
    liveUrl: "https://gap-finder-nyc.vercel.app",
    flagship: false,
  },
  {
    name: "Not That Unique NYC",
    slug: "not-that-unique-nyc",
    tagline: "How unique is your NYC neighborhood, really? Compare stats block by block.",
    domain: "nyc",
    tech: ["React", "TypeScript", "Census API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/not-that-unique-nyc",
    liveUrl: "https://ntun-nyc.vercel.app",
    flagship: false,
  },
  {
    name: "Give Local NYC",
    slug: "give-local-nyc",
    tagline: "Volunteer opportunity matcher. Short quiz, weighted matching engine, 120 NYC-area organizations.",
    domain: "nyc",
    tech: ["React", "TypeScript", "Matching Engine"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/give-local-nyc",
    liveUrl: "https://give-local-nyc.vercel.app",
    flagship: false,
  },

  // ── Music ──────────────────────────────────────────────────────────
  {
    name: "Air Composer",
    slug: "air-composer",
    tagline: "Play a theremin with your hands using just a webcam. Wave to make music.",
    domain: "music",
    tech: ["TypeScript", "MediaPipe", "Web Audio API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/photo-booth-music",
    liveUrl: "https://air-composer.vercel.app",
    flagship: false,
  },
  {
    name: "Keyboard Drummer",
    slug: "keyboard-drummer",
    tagline: "Turn your keyboard into a drum kit. 5 songs, rhythm scoring, full session playback.",
    domain: "music",
    tech: ["JavaScript", "Web Audio API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/keyboard-drummer",
    liveUrl: "https://keyboard-drummer.vercel.app",
    flagship: false,
  },
  {
    name: "Popup Beat Panic",
    slug: "popup-beat-panic",
    tagline: "Rhythm game disguised as an IE nightmare. Close popups to the beat.",
    domain: "music",
    tech: ["JavaScript", "Web Audio API", "Canvas"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/popup-beat-panic",
    liveUrl: "https://michaelpyon.github.io/popup-beat-panic/",
    flagship: false,
  },
  {
    name: "Vinyl Discovery",
    slug: "vinyl-discovery",
    tagline: "Interactive 3D globe for discovering vinyl record stores worldwide.",
    domain: "music",
    tech: ["React", "Three.js", "TypeScript"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/vinyl-discovery",
    liveUrl: "https://vinyl-discovery.vercel.app",
    flagship: false,
  },
  {
    name: "Concert Playlist",
    slug: "concert-playlist",
    tagline: "Auto-generate Spotify playlists from any artist's upcoming tour setlist.",
    domain: "music",
    tech: ["TypeScript", "Spotify API", "Setlist.fm API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/concert-playlist",
    liveUrl: "https://concert.michaelpyon.com",
    flagship: false,
  },
  {
    name: "Jazz Guitar Solo",
    slug: "jazz-guitar-solo",
    tagline: "Improvise jazz guitar lines over chord changes with AI-assisted scale suggestions.",
    domain: "music",
    tech: ["JavaScript", "Web Audio API", "Tone.js"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/jazz-guitar-solo",
    liveUrl: null,
    flagship: false,
  },

  // ── Games ──────────────────────────────────────────────────────────
  {
    name: "ShooterDigest",
    slug: "shooterdigest",
    tagline: "Weekly competitive shooter intelligence briefing. Player stats, meta shifts, patch notes.",
    domain: "games",
    tech: ["React", "TypeScript", "Tracker.gg API"],
    date: "2026-02",
    url: "https://github.com/michaelpyon/ShooterDigest",
    liveUrl: "https://shooter-digest-app.vercel.app",
    flagship: false,
  },
  {
    name: "Studio Commander",
    slug: "studio-commander",
    tagline: "Strategy sim. Run a fictional multiplayer shooter studio across a 12-turn live-ops campaign.",
    domain: "games",
    tech: ["React", "TypeScript", "Game Engine"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/studio-commander",
    liveUrl: "https://studio-commander.vercel.app",
    flagship: false,
  },
  {
    name: "Rhythm Typer",
    slug: "rhythm-typer",
    tagline: "Type words to destroy sharks swimming toward you, timed to a beat for combo multipliers.",
    domain: "games",
    tech: ["JavaScript", "Canvas", "Web Audio API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/rhythm-typer",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Lockstep",
    slug: "lockstep",
    tagline: "March in lockstep and hit on-beat cues in a minimalist rhythm game.",
    domain: "games",
    tech: ["JavaScript", "Canvas", "Web Audio API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/lockstep",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Excel Escape",
    slug: "excel-escape",
    tagline: "Escape a dungeon by solving Excel-style formula challenges. Puzzle meets spreadsheet.",
    domain: "games",
    tech: ["JavaScript", "React", "Formula Parser"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/excel-escape",
    liveUrl: "https://excel-escape.vercel.app",
    flagship: false,
  },
  {
    name: "Freeze Frame",
    slug: "freeze-frame",
    tagline: "Spot-the-difference meets speed run. Freeze the frame, find what changed.",
    domain: "games",
    tech: ["JavaScript", "Canvas", "React"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/Freeze-Frame-Claude",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Inflation Race",
    slug: "inflation-race",
    tagline: "Roguelike economics arcade game. Outrun inflation through procedurally generated market events.",
    domain: "games",
    tech: ["React", "Canvas", "Game Loop"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/inflation-race",
    liveUrl: "https://inflation-race.vercel.app",
    flagship: false,
  },
  {
    name: "High Roller",
    slug: "high-roller",
    tagline: "Dice roller with streak multiplier, celebrations, and snake eyes mode.",
    domain: "games",
    tech: ["React", "TypeScript", "Framer Motion"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/high-roller",
    liveUrl: "https://high-roller-eight.vercel.app",
    flagship: false,
  },
  {
    name: "Bomb Council",
    slug: "bomb-council",
    tagline: "Multiplayer deduction game. Find the bomber before time runs out. Bluffing required.",
    domain: "games",
    tech: ["JavaScript", "WebSocket", "Canvas"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/bomb-council",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Dice",
    slug: "dice",
    tagline: "Minimalist animated dice roller with clean physics and satisfying rolls.",
    domain: "games",
    tech: ["JavaScript", "CSS Animations"],
    date: "2026-02",
    url: "https://github.com/michaelpyon/dice",
    liveUrl: null,
    flagship: false,
  },

  // ── Tools ──────────────────────────────────────────────────────────
  {
    name: "Food Council Tokyo",
    slug: "food-council-tokyo",
    tagline: "Curated Tokyo restaurant guide. Neighborhood-based food discovery.",
    domain: "tools",
    tech: ["React", "TypeScript", "Mapbox"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/food-council-tokyo",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Inner Circle",
    slug: "inner-circle",
    tagline: "Personal CRM for keeping track of the people who matter most.",
    domain: "tools",
    tech: ["React", "TypeScript", "Local Storage"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/inner-circle",
    liveUrl: "https://inner-circle-crm.vercel.app",
    flagship: false,
  },
  {
    name: "Dice Roller",
    slug: "dice-roller",
    tagline: "Animated dice roller with realistic dot faces and particle burst effects.",
    domain: "tools",
    tech: ["JavaScript", "Canvas", "CSS Animations"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/dice-roller",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "MassageOS",
    slug: "massage-os",
    tagline: "Massage practice management system. Scheduling, client tracking, and session notes.",
    domain: "tools",
    tech: ["React", "TypeScript", "Node.js"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/massage-os",
    liveUrl: "https://massage-os-deploy.vercel.app",
    flagship: false,
  },
  {
    name: "NK-Book",
    slug: "nk-book",
    tagline: "Korean book OCR, translation, and validation pipeline. Scanned pages to verified English.",
    domain: "tools",
    tech: ["Python", "OCR", "Translation API"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/nk-book",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Fresh Bowl",
    slug: "fresh-bowl",
    tagline: "Pet bowl cleaning reminder app with SMS nudges and streak tracking.",
    domain: "tools",
    tech: ["React", "TypeScript", "Twilio"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/fresh-bowl",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Fresh Sheets",
    slug: "fresh-sheets",
    tagline: "Sheet washing reminder with SMS verification, streak tracking, and cleanliness tiers.",
    domain: "tools",
    tech: ["React", "TypeScript", "Twilio"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/fresh-sheets",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Quench",
    slug: "quench-hydration",
    tagline: "SMS-first hydration reminder. Short quiz, personalized water reminders throughout the day.",
    domain: "tools",
    tech: ["React", "TypeScript", "Twilio"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/quench-hydration",
    liveUrl: null,
    flagship: false,
  },
  {
    name: "Rice Cooker Timer",
    slug: "rice-cooker-timer",
    tagline: "Dead-simple rice cooker countdown timer. One page, no dependencies.",
    domain: "tools",
    tech: ["HTML", "JavaScript", "CSS"],
    date: "2026-02",
    url: "https://github.com/michaelpyon/rice-cooker-timer",
    liveUrl: null,
    flagship: false,
  },

  // ── New additions ──────────────────────────────────────────────────
  {
    name: "Sunscope",
    slug: "sunscope",
    tagline: "Track sun position, golden hour, and shadow direction on a live map. Built with SunCalc and MapLibre.",
    domain: "tools",
    tech: ["React", "TypeScript", "MapLibre", "SunCalc"],
    date: "2026-04",
    url: "https://github.com/michaelpyon/sunscope",
    liveUrl: "https://sunscope-eta.vercel.app",
    flagship: false,
  },
  {
    name: "Chief Jumper",
    slug: "chief-jumper",
    tagline: "Endless runner with a corporate twist. Jump obstacles, climb the org chart, survive the office.",
    domain: "games",
    tech: ["JavaScript", "Canvas", "Sprite Animation"],
    date: "2026-03",
    url: "https://github.com/michaelpyon/ChiefJumper-Claude",
    liveUrl: null,
    flagship: false,
  },
];

export const domains: Domain[] = ["finance", "nyc", "games", "music", "tools", "data"];

export const domainLabels: Record<Domain, string> = {
  finance: "Finance",
  nyc: "NYC",
  games: "Games",
  music: "Music",
  tools: "Tools",
  data: "Data",
};

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getFlagshipProjects(): Project[] {
  return projects.filter((p) => p.flagship);
}

export function getProjectsByDomain(domain: Domain): Project[] {
  return projects.filter((p) => p.domain === domain);
}
